### ISSUE TITLE
functions.getsettings throws UnboundMethod exception

### ISSUE THREAD

**Issue by taMiF** [alvra/django-usersettings#4]
Calling functions.getsettings() I get the following execption:

``` python
File "/home/.../django/.virtualenvs/.../lib/python2.7/site-packages/usersettings/functions.py", line 49, in getsettings
    settings[setting.name] = setting.default()
TypeError: unbound method default() must be called with NotifyAtLoginSetting instance as first argument (got nothing instead)
```

At a first glance the problem might be SettingsRegister.register never instanciating given Setting classes. Yet methods aren't  classmethods, nor given an object. Registering instances solved the problem and seems to be correct way.

**Comment by alvra** [comment]
I'm aware the docs are lacking, which is probably the issue here. You're right that Setting instances should be registered.
